import type { EvidenceEdgeData, EvidenceNodeData } from "./types";

export const demoNodes: EvidenceNodeData[] = [
  {
    id: "seed",
    label: "qq101uok.com",
    detail: "Public seed domain",
    kind: "domain",
    x: 350,
    y: 260,
    step: 0,
    source: "https://qq101uok.com/",
    state: "verified",
  },
  {
    id: "contact",
    label: "/Contact",
    detail: "Preserved page",
    kind: "page",
    x: 190,
    y: 155,
    step: 1,
    source: "https://qq101uok.com/Contact",
    state: "verified",
  },
  {
    id: "telegram",
    label: "@qq101_support",
    detail: "Telegram handle",
    kind: "telegram",
    x: 76,
    y: 65,
    step: 2,
    source: "Visible text on /Contact",
    state: "verified",
  },
  {
    id: "phone",
    label: "+63 915 780 0101",
    detail: "Phone number",
    kind: "phone",
    x: 96,
    y: 330,
    step: 2,
    source: "Visible text on /Contact",
    state: "verified",
  },
  {
    id: "whatsapp",
    label: "+63 954 335 5092",
    detail: "WhatsApp identifier",
    kind: "whatsapp",
    x: 320,
    y: 455,
    step: 2,
    source: "Public contact route",
    state: "verified",
  },
  {
    id: "candidate",
    label: "qq101uok.net",
    detail: "Candidate domain",
    kind: "domain",
    x: 615,
    y: 215,
    step: 4,
    source: "Shared public identifier",
    state: "pending",
  },
  {
    id: "rejected",
    label: "qq101-news.example",
    detail: "Rejected relation",
    kind: "domain",
    x: 610,
    y: 385,
    step: 4,
    source: "Human review decision",
    state: "rejected",
  },
];

export const demoEdges: EvidenceEdgeData[] = [
  {
    id: "seed-contact",
    source: "seed",
    target: "contact",
    label: "captured",
    state: "verified",
    step: 1,
  },
  {
    id: "contact-telegram",
    source: "contact",
    target: "telegram",
    label: "observed on",
    state: "verified",
    step: 2,
  },
  {
    id: "contact-phone",
    source: "contact",
    target: "phone",
    label: "observed on",
    state: "verified",
    step: 2,
  },
  {
    id: "contact-whatsapp",
    source: "contact",
    target: "whatsapp",
    label: "observed on",
    state: "verified",
    step: 2,
  },
  {
    id: "seed-candidate",
    source: "seed",
    target: "candidate",
    label: "candidate",
    state: "pending",
    step: 4,
  },
  {
    id: "seed-rejected",
    source: "seed",
    target: "rejected",
    label: "rejected",
    state: "rejected",
    step: 4,
  },
];
